# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='lock',
            field=models.BooleanField(default=True),
        ),
    ]
