# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('book', '0002_topic_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sent', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Completion')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Topic')),
            ],
        ),
    ]
