# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190702_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
