# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-01 17:38
from __future__ import unicode_literals

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stattypeus', models.CharField(choices=[(1, b'IMAGE'), (2, b'CODE'), (3, b'TEXT'), (4, b'TABLE'), (5, b'POINTS'), (6, b'GRAPH'), (7, b'LINK'), (8, b'VIDEO')], default=3, max_length=20)),
                ('position', models.IntegerField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=book.models.get_topic_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('position', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=book.models.get_topic_image_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Course')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Topic'),
        ),
    ]
