TEXT = 1
CODE = 2
IMAGE = 3
POINT = 4
LINK = 5
GRAPH = 6
TABLE = 7
VIDEO = 8

# TYPE_CHOICES = (
#     (IMAGE, 'IMAGE'),(CODE,'CODE'),(TEXT, 'TEXT'),
#     (TABLE,'TABLE'), (POINTS, 'POINTS'), (GRAPH, 'GRAPH'),
#     (LINK, 'LINK'), (VIDEO, 'VIDEO')
# )